//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnover_SA_de_CV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concierto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Concierto()
        {
            this.Entradas = new HashSet<Entrada>();
            this.HistorialCompras = new HashSet<HistorialCompra>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaConcierto { get; set; }
        public string Lugar { get; set; }
        public int EntradasPlateaDisponibles { get; set; }
        public int EntradasVIPDisponibles { get; set; }
        public int EntradasGeneralDisponibles { get; set; }
        public decimal PrecioPlatea { get; set; }
        public decimal PrecioVIP { get; set; }
        public decimal PrecioGeneral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrada> Entradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialCompra> HistorialCompras { get; set; }
    }
}
