//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnover_SA_de_CV
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialCompra
    {
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public int ConciertoId { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public int TotalComprado { get; set; }
    
        public virtual Concierto Concierto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
