//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnover_SA_de_CV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Turnover_databaseEntities1 : DbContext
    {
        public Turnover_databaseEntities1()
            : base("name=Turnover_databaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Concierto> Conciertos { get; set; }
        public virtual DbSet<Entrada> Entradas { get; set; }
        public virtual DbSet<HistorialCompra> HistorialCompras { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
